### ISSUE TITLE
Update code to newer version?

### ISSUE THREAD

**Issue by madprops** [wdlkmpx/osmo#1]
I'm glad there's a github repo for osmo, to work as a mirror I guess, unless you're the original author. 
Just wondering if you plan to update the code at all once in a while, osmo is already at version 0.4.2 here.

**Comment by wdlkmpx** [comment]
I'm not the original author. I created this repo to fix an old version that is used in certain lightweight distro.

This still uses libgtkhtml for the Contacts (or something), in a later version they switched to libwebkitgtk which is huge.

In fact, osmo doesn't need any of those libs, it's possible to specify colors, sizes, etc in a GtkTreeView without a huge external lib, probably they never figured out it was possible.

**Comment by madprops** [comment]
I see, so it's a legit fork. After doing some searches I think the change to libwebkitgtk might have been due to distros stopping to distribute libgtkhtml: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=797429
