### ISSUE TITLE
Osmo crashes when create a new contact

### ISSUE THREAD

**Issue by bkauler** [wdlkmpx/osmo#2]
Hi,
This is a very old problem, see this thread in the old Puppy Murga Forum:

http://www.murga-linux.com/puppy/viewtopic.php?t=115567

...they have determined that it works with libxml2 2.8.0, crashes with 2.9.x.

I have today compiled osmo in EasyOS 2.6.2 Dunfell-series, tried to create a contact, same crash.

**Comment by bkauler** [comment]
libxml2 2.8.0 won't compile, a function is missing.
I compiled with libxml2 2.9.0 and that works.

What I did was link with libxml2.a from the 2.9.0 build, so it was statically linked in the osmo executable. That way, it runs in EasyOS with later libxml shared libs.

**Comment by wdlkmpx** [comment]
I guess the last time I used Osmo was to create this repo. It was determined that the crash happens in libgtkhtml

Here is a libgtkhtml with some cleanups, autotools updates and a hack for libxml 2.9
https://github.com/wdlkmpx/libgtkhtml2/

It was a bad idea to rely on an external library to display contact info or something, it can be done with a GtkTreeView applying certain text attributes to specific rows, columns or cells.
https://stackoverflow.com/questions/49836499/make-only-some-rows-bold-in-a-gtk-treeview

**Comment by bkauler** [comment]
Closed
